import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Link from "next/link";

const layout = (props) => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <Link href="/">My Portfolio</Link>
      </h1>

      <p className={styles.description}>
        <code className={styles.code}>
          I&apos;m Jose L Hernandez, nice to meet you!
        </code>
      </p>

      { props.children }

    </main>

    <footer className={styles.footer}>
      <p>&copy; Jose L Hernandez 2022</p>
    </footer>
  </div>
);

export default layout;
