import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Link from "next/link";
import Script from "next/script";

const layout = (props) => {
  const discord = () => {
    if (typeof window !== "undefined") {
      alert("luis11#6236");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Jose L Hernandez | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon1.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/">My Portfolio</Link>
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>
            I&apos;m Jose L Hernandez, nice to meet you!
          </code>
        </p>

        {props.children}
      </main>

      <footer className={styles.footer}>
        <p>&copy; Jose L Hernandez 2022</p>
        <a
          href="https://www.linkedin.com/in/jhernandez-11/"
          target="_blank"
          rel="noreferrer"
          className="gIcon"
        >
          <ion-icon name="logo-linkedin"></ion-icon>
        </a>
        <a
          href="https://github.com/jhernandez-11"
          target="_blank"
          rel="noreferrer"
          className="gIcon"
        >
          <ion-icon name="logo-github"></ion-icon>
        </a>
        <a href="#" id="discord" className="gIcon" onClick={discord}>
          <ion-icon name="logo-discord"></ion-icon>
        </a>
      </footer>

      <Script
        type="module"
        src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
      ></Script>
      <Script
        nomodule
        src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
      ></Script>
    </div>
  );
};

export default layout;
